Draft: Add reports in LfNetworkLoaderImpl
powsybl/powsybl-open-loadflow pull request #1020
Opened 2024-04-18 09:22 UTC by caioluke

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

The class LfNetworkLoaderImpl has a lot of information logged via the LOGGER, but the same information is not reported in the ReportNode API.

**What is the new behavior (if this is a feature change)?**
Important information will also be reported in the ReportNode API.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

2024-04-25 08:14 UTC, jeandemanged commented
@caioluke please sign your commits and force push

2024-04-25 08:39 UTC, jeandemanged requested changes

2024-04-25 08:39 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/util/Reports.java
> +                .withMessageTemplate("notUniqueTargetVControllerBus", "Generators [${generatorIds}] are connected to the same bus ${controllerBusId} with different target voltages: ${keptTargetV} (ke
```suggestion
                .withMessageTemplate("notUniqueTargetVControllerBus", "Generators [${generatorIds}] are connected to the same bus ${controllerBusId} with different target voltages: ${keptTargetV} kV (kept) and ${rejectedTargetV} kV (rejected)")
```

2024-04-25 08:39 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/util/Reports.java
> +                .withMessageTemplate("busAlreadyControlledWithDifferentTargetV", "Bus ${controllerBusId} controls voltage of bus ${controlledBusId} which is already controlled by buses [${busesId}] w
```suggestion
                .withMessageTemplate("busAlreadyControlledWithDifferentTargetV", "Bus ${controllerBusId} controls voltage of bus ${controlledBusId} which is already controlled by buses [${busesId}] with a different target voltage: ${keptTargetV} kV (kept) and ${ignoredTargetV} kV (ignored)")
```

2024-04-25 08:39 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/util/Reports.java
> +                .withMessageTemplate("branchControlledAtBothSides", "Controlled branch ${controlledBranchId} is controlled at both sides. Controlled side ${keptSide} (kept) ${rejectedSide} (rejected)
```suggestion
                .withMessageTemplate("branchControlledAtBothSides", "Controlled branch ${controlledBranchId} is controlled at both sides. Controlled side ${keptSide} (kept) side ${rejectedSide} (rejected).")
```

2024-04-25 08:39 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/util/Reports.java
> +import com.powsybl.iidm.network.TwoSides;
don't import iIDM in here

2024-04-25 08:39 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
> +    private static void createVoltageControls(List<LfBus> lfBuses, LfNetworkParameters parameters, ReportNode reportNode) {
here and in many places after, don't add this argument in method signature. Instead, you should be able to get the LfNetwork report node by doing `someBus.getNetwork().getReportNode()`

2024-04-29 10:22 UTC, jeandemanged requested changes
there is a merge commit you did locally that you have to sign ...

2024-04-29 10:22 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
> +                    generatorReactivePowerControl.getControlledBranch().getId(), String.valueOf(generatorReactivePowerControl.getControlledSide()), String.valueOf(side));
use `someEnumValue.name()` instead of `String.valueOf(someEnumValue)`

2024-05-13 13:06 UTC, jeandemanged approved these changes

2024-05-13 13:15 UTC, jeandemanged requested changes
please cover also `checkUniqueControlledBus`

2024-05-15 16:44 UTC, jeandemanged approved these changes

2024-05-16 06:42 UTC, geofjamg approved these changes

2024-05-16 06:42 UTC, merged