Reduce irrealistic voltage created by remote voltage control
powsybl/powsybl-open-loadflow pull request #1135
Opened 2024-11-27 11:59 UTC by vidaldid-rte

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
Fixes #1124

**What kind of change does this PR introduce?**
A new parameter, **voltageRemoteControlRobustMode** is introduced. With value true by default.
When the robust mode is set to true, 
 - The enforcement of realistic voltage limit is performed only after the reactive limit outerloop is stabilized

the reactive limit outerloop is modified as follow:

If the bus of a generator with remote voltage control on , and reactivie limits, is approaches the realistic voltage limit:
    - If the bus is outside its reactive limits, it is move PQ (as usual) and its voltage is set to 1pu for the next NR run
    - If the bus is inside its reactive limites, it is removed from voltage control (and Q is set to initial targetQ). Its voltage is set to 1pu for the next NR run.

**What is the current behavior?**
The Newton Raphson fails if a bus reaches a low voltage - a situation that can happen with remoted voltage control due to the PQV model.

**What is the new behavior (if this is a feature change)?**
With **voltageRemoteControlRobustMode** set to true (the default value) the resolution of networks with stressed or inconsistent remote voltage targets is more robust.

**Does this PR introduce a breaking change or deprecate an API?**
- [] Yes
- [ X ] No

2025-01-15 14:07 UTC, SylvestreSakti reviewed
Some minor remarks on the code and I did some typo fix.

2025-01-15 14:07 UTC, SylvestreSakti commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
>       *  - if Q equals to Qmin
This comment should be updated :
```suggestion
     * (1) A bus PV bus can be switched to PQ in 3 cases:
     *  - if Q equals to Qmax
     *  - if Q equals to Qmin
     *  - if the controller bus is a remote controller bus and V is outside realistic voltage limits
```

2025-01-15 14:07 UTC, SylvestreSakti commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
> +                        LOGGER.trace("Remote reactive power controller bus '{}' -> PQ = targetQ - v outside realistic voltage limits",
Same remark as above

2025-01-15 15:40 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
> +        if (!canCheckUnrealistic && runningContext.lastUnrealisticStateFixingLoop == outerLoop && runningContext.lastSolverResult.getStatus() == AcSolverStatus.CONVERGED) {
It is equivalent if you take into account that canCheckUnrealistic is defined today by "runningContext.lastUnrealisticStateFixingLoop == null"

But I prefer to explicit the condition to avoid side effect if that definition is changed.

The meaning is:
  if canCheckUnrealistic is false, then the check was not performed in solver.run
  And if we are the last outerloop that tolerates unrealistic voltage, then we must check if the loop has converged.
  
  I prefer to keep it written this way instead of assuming relationships between these variables.

2025-01-15 15:43 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
> +            if (solver.isStateUnrealisticForSolver(context.getNetwork().getReportNode())) {
I wanted to explicit the conditions.
My logic is:
First condition; we have to check now the irrealistic values.
Second condition:
   We test the values (it is not only a test since it generates a report by the way and has really to be done if previou sconditions are true)
      and f they are irrealistic we update the result.

2025-01-15 15:56 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
> +                            LOGGER.trace("Switch bus '{}' PV -> PQ, q={} = targetQ - v outside realistic voltage limits", controllerBus.getId(), pvToPqBus.qLimit * PerUnit.SB);
Why not adding the voltage. But my intention was mostly to tell that the bus is switch to PQ with Q = target Q which is unusual. Displaying targetQ is important to me because it explain the results (and I think it disappears from your suggested message and is replaced by the  of the bus when in irrealistic conditions)

2025-01-15 16:20 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
> +            if (solver.isStateUnrealisticForSolver(context.getNetwork().getReportNode())) {
I rewrote the part to avoid making Sonar believe this is just boolean arithmetic...

2025-01-15 16:21 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
> +                            LOGGER.trace("Switch bus '{}' PV -> PQ, q={} = targetQ - v outside realistic voltage limits", controllerBus.getId(), pvToPqBus.qLimit * PerUnit.SB);
Trace Message updated with bus V and limits.

2025-01-15 16:22 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
> +                        LOGGER.trace("Remote reactive power controller bus '{}' -> PQ = targetQ - v outside realistic voltage limits",
Info added but targetQ kept.

2025-02-03 09:38 UTC, SylvestreSakti commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
> +        return true;
Shouldn't we check unrealistic state if robust mode is deactivated ?

If voltageRemoteControlRobustMode is set to `false`, I would put the value canFixUnrealisticState at `false` for this outerloop.

2025-02-03 13:27 UTC, SylvestreSakti commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
> +        return true;
After discussion, this value can stay to `true` because when the parameter `voltageRemoteControlRobustMode` is deactivated, `canFixUnrealisticState()` is not called.

2025-02-03 14:44 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
> +        return true;
@SylvestreSakti after more thought I still think the outerloop should return true whether or not robustMode is true.
Here is why:
   Even passively, the outerloop can fix some irrealistic voltage (as noticed by Sebastien in PR #1087 
   This is also the case of the TrasformerVoltageControlOuterloop that can passively fix irrealistic voltages (that it may introduce when unstable when continuous tapratio are not within their bounds)

    So if in the future, someone wanted to delay voltage control after this outerloop, even if the ReactiveLimitOuterloop does nothing about robustification ( reset unrealistiv V to 1, or to set PQ controller buses within diagram but outside realistic voltage), he could implement this using this method.

2025-02-03 16:24 UTC, SylvestreSakti approved these changes

2025-02-06 09:20 UTC, jeandemanged requested changes
ok for me, except one API design topic (AcSolver) that needs to be though about maybe.
Otherwise just minor comments.

2025-02-06 09:20 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java
> +    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode, boolean canCheckUnrealistic);
no strong opinion here... asking @geofjamg also for advice...
My understanding is that now the AcSolver needs to know things happening in AcLoadFlowEngine and OuterLoops.
Would it make sense instead to:
- move `canCheckUnrealistic` to `AcLoadFlowContext`
- change the API to provide the `AcSolver` with the `AcLoadFlowContext` 
?

2025-02-06 09:20 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/network/LfBus.java
> +        MAX_V;
minor: rename to `MIN/MAX_REALISTIC_V` ? (just for extra clarity)

2025-02-06 09:20 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
do you need these changes ?

2025-02-06 09:20 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
> +    }
do you need to keep this ?

2025-02-06 09:20 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
> +            assertReactivePowerEquals(-10, g1.getTerminal());  // The group is set to initial targetQ
group  -> generator (also 2 times below)

2025-02-06 09:20 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
> +     *  b2 ----------------l23-------------b3---l3 (100mW)
kv -> kV
mW -> MW

2025-02-06 09:48 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java
> +    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode, boolean canCheckUnrealistic);
Indeed unrealistic state management could be seen as a hack compared to a clean modeller/solver design where in theory the solver should not known anything regarding the physics behing the equations to solve.
Looking at the code (to confirm) we should be able to move unrealistic state management out of the solver (check is done at the very end of the solve) and have all these code in the AcLoadFlowEngine which would be a cleaner design. Also the second solver Newton krylov would also befinit from it which is not the case here.

2025-02-06 09:50 UTC, geofjamg requested changes

2025-02-06 09:50 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
Instead of adding this new parameter, we could just replace voltageRemoteControl by a 3 values enum. That would simplify the configuration.

2025-02-06 10:04 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
I see issues with that:
    - it is a breaking change
    - it is harder for users to use an enum value than using boolean values
    - how to make it the default ?

Now to brainstorm on the enum idea, we could consider
voltageRemoteControl:
     Off
     Robust
     Fragile ?

2025-02-06 10:11 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
Another proposal to kepp compatibility and have robust by default

false
true    (with robust)
reactiveLimitsOnly  (the original algo)

2025-02-06 10:17 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java
> +    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode, boolean canCheckUnrealistic);
> Looking at the code (to confirm) we should be able to move unrealistic state management out of the solver (check is done at the very end of the solve) and have all these code in the AcLoadFlowEngine which would be a cleaner design. Also the second solver Newton krylov would also befinit from it which is not the case here.

Thanks for feedback, indeed if possible this would be the ideal solution. As I see it unrealistic state management is in NR solver only for historical reasons and should probably be moved out.

2025-02-06 10:19 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
To keep backward compatibility you just have to keep voltageRemoteControl and setter and getter that set the corresponding mode and manage it when loading from platform config / json.
Values could be 
ON,
ON_ROBUST,
OFF

But maybe it would not worth the dev effort.

2025-02-06 10:19 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java
> +    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode, boolean canCheckUnrealistic);
Yes, it is an already existing design issue even if not as visible as with this PR because only part of the solver API because of the return status.

2025-02-06 10:22 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
After more thought let's keep it as it is as for backward compatibility especially for pypowsybl we would need to keep old parameter and make a hack for that.

2025-02-06 10:23 UTC, vidaldid-rte commented on src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
> +    }
In reality the PV/PQ switches should probably be in the reports. 
It is useful information today. And with robust mode it would provide an explanation for PQ groups not a reactive limit bounds.

@geofjamg @jeandemanged  keep the info in logs today should I use this PR to move the PQ changes to the reports ?

2025-02-06 10:24 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
I'd go for OFF/ON/ROBUST
Robust can be the default.
For backward compat we may map `false` to OFF and `true` to ROBUST (in OpenLoadFlowParameters#update).
Note: be careful of pypowsybl users which may provide `True`/`False` and not `true`/`false`.

2025-02-06 11:25 UTC, vidaldid-rte commented on src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
> +    }
logger activation removed.

2025-02-06 11:29 UTC, vidaldid-rte commented on src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
> +            assertReactivePowerEquals(-10, g1.getTerminal());  // The group is set to initial targetQ
Done

2025-02-06 11:29 UTC, vidaldid-rte commented on src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
> +     *  b2 ----------------l23-------------b3---l3 (100mW)
Done

2025-02-06 11:56 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/network/LfBus.java
> +        MAX_V;
Done

2025-02-06 12:30 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
oh sonar was the reason behind ... worst case this can be bypassed for merging, sonar most of the time points real issues, but occasionally may be too much a pain for just nothing.

2025-02-06 15:42 UTC, vidaldid-rte commented on src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
@geofjamg @jeandemanged 
Reporting the PV P switches is a bit large. I speparated into a different PR to merge after that one (https://github.com/powsybl/powsybl-open-loadflow/pull/1182)
This means that we may have to shut down Sonar alert on test coverage for that PR, or restore the LOGGER trace activation hack.

2025-02-10 10:07 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java
> +    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode, boolean canCheckUnrealistic);
FYI, I'll create a separate PR to extract the voltage verification from Newton Raphson.

2025-02-10 15:19 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java
> +    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode, boolean canCheckUnrealistic);
@geofjamg  @jeandemanged  the PR to move the irrealistic voltage verification is here https://github.com/powsybl/powsybl-open-loadflow/pull/1188 . To be merged in main before that one on irrealistic voltage (and then I will adapt that one).

2025-02-10 16:41 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
@jeandemanged  I would vote like Geoffroy and keep as it is. I do not see an easy way to change voltageRemoteControl to an enum without creating a breaking change in one of the following:
         JSON,  the Java parameter API or in pypowsybl.

It believe that the way to change a parameter from bool to enum would be to deprecate the old one and create a new one that would be enum based. But it seems overkill here.

2025-02-10 16:55 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
I am ok with this no problem, my last message was sent almost same time as Geoffroy's one, I was just slower by 1 minute :)
Agree to keep as it is.

2025-02-11 17:33 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java
> +    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode, boolean canCheckUnrealistic);
Merged. Requesting new review.

2025-02-12 09:29 UTC, vidaldid-rte commented on src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
After more thought I reintroduced the trace log for the two tests.
I think it is good that the code that generates trace logs in the ReactiveLimitsOuterLoop is run at least once per build. This ensures that this won't break if someone needs to activate this log level for the class. So for me it justifies that we merge that.
And for this PR that was freshly refactored (moving up the realistic check) it is good to have a solide test coverage measure and easily spot was is left untested.

2025-02-19 10:01 UTC, jeandemanged requested changes
Thank you, just minor polishing to do.

Please also update the PR description:
- not a breaking change anymore
- mention the new parameter and its default value

2025-02-19 12:28 UTC, jeandemanged approved these changes

2025-02-19 12:33 UTC, merged