[WIP] Security Analysis: custom redistribution of injections lost by the contingency
powsybl/powsybl-open-loadflow pull request #1155
Opened 2024-12-16 17:43 UTC by jeandemanged

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

#1092 

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

When a contingency trips an injection and slack distribution enabled (or area interchange control), the missing active power is distributed using the configured balance type.

**What is the new behavior (if this is a feature change)?**
OLF provides a way to configure this redistribution externally via plugin mecanism (ServiceLoader).

**Does this PR introduce a breaking change or deprecate an API?**
- [x] No

2025-02-12 09:52 UTC, vidaldid-rte commented on docs/security/parameters.md
> +- distributes the active power imbalance according the configured BalanceType
according **to** ?

2025-02-12 09:57 UTC, vidaldid-rte commented on docs/security/parameters.md
> +an implementation of the `ContingencyActivePowerLossDistribution` interface and make this implementation available to the
This useful doc doesn't really belong to parameters.
Maybe time to providing a "plugin programming guide" and start with this content (and reference it in the param doc )?

2025-02-12 10:45 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +        ContingencyActivePowerLossDistribution contingencyActivePowerLossDistribution = ContingencyActivePowerLossDistribution.find(openSecurityAnalysisParameters.getContingencyActivePowerLossDistrib
This query seems a bit heavy (it involves querying a class loader to find the right service).
Can you move it up to a place where it is less frequently used ? (here it is once par component and per thread in MT SA).

2025-02-12 12:40 UTC, vidaldid-rte requested changes
I'm globally OK with this PR. Few remarks on doc and plugin initialisation.

2025-02-12 15:46 UTC, jeandemanged commented on docs/security/parameters.md
> +an implementation of the `ContingencyActivePowerLossDistribution` interface and make this implementation available to the
agree, let me know if ok with proposed structure

2025-02-14 08:34 UTC, vidaldid-rte commented on docs/security/parameters.md
> +an implementation of the `ContingencyActivePowerLossDistribution` interface and make this implementation available to the
I think that the programming guide could be a section in its own (in addition to loadflow, security, sensitivity) and cover all plugins we want to document. For example if we wanted to document the ACSolver extension it could be here, or how to create an OUterLoop.
What do you think ?.

2025-02-14 09:01 UTC, vidaldid-rte commented on docs/security/parameters.md
> +- Customizing the way contingency imbalances are compensated via `contingencyActivePowerLossDistribution` parameter is not supported.
Should be one line later because "as a result..." refers to the slack relocation limitation.

2025-02-14 16:17 UTC, vmouradian commented on docs/security/parameters.md
> +- Customizing the way contingency imbalances are compensated via `contingencyActivePowerLossDistribution` parameter is not supported.
fixed in [e74f9cc](https://github.com/powsybl/powsybl-open-loadflow/pull/1155/commits/e74f9cccd0250ec5ba445803e171ca38b3fcf0cd)

2025-02-14 16:17 UTC, vmouradian approved these changes

2025-02-17 17:55 UTC, jeandemanged commented on docs/security/parameters.md
> +an implementation of the `ContingencyActivePowerLossDistribution` interface and make this implementation available to the
Hi @vidaldid-rte , makes perfectly sense, can you check the proposed structure as it is now and provide early feedback?
https://powsybl--1155.org.readthedocs.build/projects/powsybl-open-loadflow/en/1155/advanced_programming/index.html

I will finalized the missing sections later on.

2025-02-18 09:08 UTC, vidaldid-rte commented on docs/security/parameters.md
> +an implementation of the `ContingencyActivePowerLossDistribution` interface and make this implementation available to the
Excellent !

2025-02-18 09:10 UTC, vidaldid-rte approved these changes

2025-02-18 17:19 UTC, merged