[WIP] Feature : SA : Use Contingency LoadFlow Parameters Extension
powsybl/powsybl-open-loadflow pull request #1156
Opened 2024-12-17 13:53 UTC by vmouradian

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Part of  https://github.com/powsybl/powsybl-open-loadflow/issues/1091

**What is the new behavior (if this is a feature change)?**
Uses the class ContingencyLoadFlowParameters created in #1139 in SA calculations

Final part of the work on https://github.com/powsybl/powsybl-open-loadflow/issues/1091

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2025-01-20 10:24 UTC, m-guibert commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +                applyAcContingencyLoadFlowParameters(acLoadFlowParameters, contingencyLoadFlowParameters, loadFlowParameters, parametersExt);
Reorder parameters parametersExt and loadFlowParameters so that applyDcContingencyLoadFlowParameters and applyAcContingencyLoadFlowParameters have similar argument lists

2025-01-20 10:24 UTC, m-guibert commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +    private void applyAcContingencyLoadFlowParameters(AcLoadFlowParameters acLoadFlowParameters, ContingencyLoadFlowParameters contingencyLoadFlowParameters, LoadFlowParameters loadFlowParameters, Op
Add javadoc and/or a few comments

2025-01-20 10:59 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +                applyAcContingencyLoadFlowParameters(acLoadFlowParameters, contingencyLoadFlowParameters, loadFlowParameters, parametersExt);
fixed in [ffb2996](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/ffb2996eaa77af2cfd81368a7fd56e9be7f498aa)

2025-01-20 10:59 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +    private void applyAcContingencyLoadFlowParameters(AcLoadFlowParameters acLoadFlowParameters, ContingencyLoadFlowParameters contingencyLoadFlowParameters, LoadFlowParameters loadFlowParameters, Op
added some in [281718e](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/281718e6428c72369b54e547748ce9ea8a9bd19d), tell me what you think of it

2025-01-22 18:16 UTC, jeandemanged requested changes
Thank you, I did some cleanup: you forgot to use the `AbstractSecurityAnalysis` / `AcSecurityAnalysis`  / `DcSecurityAnalysis`  inheritance, making this simpler imho.

But there is some more work needed about outerloop reconfiguration, I wrote a suggestion, let me know what you think.

2025-01-22 18:16 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java
> +        contingencyLoadFlowParameters.isAreaInterchangeControl().ifPresent(aic -> {
same comment as for Ac

2025-01-22 18:16 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
> -        mainNetwork = lfNetworks.get(0);
add a note in the PR description for this change (LfArea-s always created by LfNetworkLoaderImpl, even if AIC disabled)

2025-01-28 21:25 UTC, jeandemanged requested changes

2025-01-28 21:25 UTC, jeandemanged commented on docs/security/parameters.md
add `outerLoopNames`

2025-01-28 21:25 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
> +        AcOuterLoopConfig outerLoopConfig = AcOuterLoopConfig.findOuterLoopConfig()
a bit worried of calling `AcOuterLoopConfig.findOuterLoopConfig()` for each contingency, probably some caching has to be implemented (look for `memoize` in other powsybl places, e.g. in core)

2025-01-28 21:25 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java
> +        DcOuterLoopConfig outerLoopConfig = DcOuterLoopConfig.findOuterLoopConfig()
same here, probably caching needed for `DcOuterLoopConfig.findOuterLoopConfig()`

2025-01-29 15:15 UTC, vmouradian commented on docs/security/parameters.md
added in [b3017c9](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/b3017c9e7904a172523ef5b0806d8a3f9490b233)

2025-01-29 15:17 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
> +        AcOuterLoopConfig outerLoopConfig = AcOuterLoopConfig.findOuterLoopConfig()
I made a proposal in [e45f710](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/e45f71078a9ddd87e7b58e228562fba507b9b11b), tell me what you think

2025-02-03 16:38 UTC, jeandemanged requested changes

2025-02-03 16:38 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/AcAreaInterchangeControlOuterLoop.java
now that you are using OuterLoopConfig-s for contingency load flow parameters, this file can be left unmodified.

2025-02-03 16:38 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java
now that you are using OuterLoopConfig-s for contingency load flow parameters, this file can be left unmodified.

2025-02-03 16:38 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlOuterLoop.java
now that you are using OuterLoopConfig-s for contingency load flow parameters, this file can be left unmodified.

2025-02-03 16:38 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AbstractAcOuterLoopConfig.java
> +    public static List<AcOuterLoop> filterInconsistentOuterLoops(List<AcOuterLoop> outerLoops) {
now that you are using OuterLoopConfig-s for contingency load flow parameters, this method can be left package-private

2025-02-03 16:38 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/sa/extensions/ContingencyLoadFlowParameters.java
mention this new parameter also in the PR description

2025-02-04 08:01 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/sa/extensions/ContingencyLoadFlowParameters.java
> +    private List<String> outerLoopNames;
must be handled also in `ContingencyLoadFlowParametersJsonSerializer`

2025-02-05 10:17 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlOuterLoop.java
done in [17045bd](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/17045bdaa391e52b14ce13747d27b550b0ff001a)

2025-02-05 10:17 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java
done in [17045bd](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/17045bdaa391e52b14ce13747d27b550b0ff001a)

2025-02-05 10:17 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/ac/outerloop/AcAreaInterchangeControlOuterLoop.java
done in [17045bd](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/17045bdaa391e52b14ce13747d27b550b0ff001a)

2025-02-05 10:17 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AbstractAcOuterLoopConfig.java
> +    public static List<AcOuterLoop> filterInconsistentOuterLoops(List<AcOuterLoop> outerLoops) {
[17045bd](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/17045bdaa391e52b14ce13747d27b550b0ff001a)

2025-02-05 11:10 UTC, jeandemanged approved these changes

2025-02-07 14:11 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
>                  .orElseGet(() -> parametersExt.getOuterLoopNames() != null ? new ExplicitAcOuterLoopConfig()
Why this change ? I belived the outerloop config for AC and DC was already in main. Why is there a need to modify it ?

2025-02-07 14:18 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
>                  .orElseGet(() -> parametersExt.getOuterLoopNames() != null ? new ExplicitAcOuterLoopConfig()
Now the config supplier is saved with Suppliers.memoize() in the abstract class to save time when creating outerloops for each contingency. So I reused the same method also here

2025-02-07 14:20 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
>                  .orElseGet(() -> parametersExt.getOuterLoopNames() != null ? new ExplicitAcOuterLoopConfig()
By the way I added a new method to OuterLoopConfig, I will update the PR with info about this change

2025-02-07 14:22 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AbstractAcOuterLoopConfig.java
> +        if (contingencyParameters.isDistributedSlack(parameters)) {
The name ContingencyParameters is confusing here. In this context there may be no contingency at all.
Suggestion:
   Can you define an interface OverridenParameters that is implemented by ContingencyParameters. At this level the OverriddenParameters would be used.

2025-02-07 14:25 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/DefaultAcOuterLoopConfig.java
> +    }
Here again, the ContingencyLoadFlowParameters is out of context.
Suggesiton:
   use again a OverriddenParameter interface, and for readibility, instead of a new use something like
   OverriddenParameter.NO_OVERRIDE;

2025-02-07 14:30 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/ExplicitAcOuterLoopConfig.java
> +    }
idem (no contingency in this context - use a more abstract interface)

2025-02-07 14:38 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
> +        // Consider only the area type that should be used for area interchange control
The fact that you removed the isAreaInterchangeControl test may penalize all applications that do not use interchange area and force to have this iteration on boundaries.
Especially, by default, getAreaInterchangeControlAreaType is defined and may exist in the file;

Can you reintroduce a flag, at least for this check.
It would take the value of the LoadFlowParameters by default.
And for AS, if false in loadFLowParameters, it would take true is some ContingencyParameters exist.

2025-02-07 14:40 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
> +        loadingContext.areaBusMap
Same comment. Can you reintroduce a flag and to the processing only when needed.

2025-02-10 11:44 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
> +        // Consider only the area type that should be used for area interchange control
fixed in [dfde7e6](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/dfde7e68ee85f4fa8bf4f4ad8c72edede51c1b3e)

2025-02-10 11:45 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
> +        loadingContext.areaBusMap
fixed in [dfde7e6](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/dfde7e68ee85f4fa8bf4f4ad8c72edede51c1b3e)

2025-02-10 11:46 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/DefaultAcOuterLoopConfig.java
> +    }
idem, see [2059100](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/20591002e5b6fb34481c07eaa3b4c350d9129657)

2025-02-10 11:51 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +        ContingencyLoadFlowParameters contingencyLfParameters = Objects.requireNonNullElse(nullableContingencyLfParameters, new ContingencyLoadFlowParameters());
fixed in [2af7dd1](https://github.com/powsybl/powsybl-open-loadflow/pull/1156/commits/2af7dd17283e4a70534e437fa933e35300b100fd)

2025-02-10 17:13 UTC, vidaldid-rte approved these changes

2025-02-11 09:20 UTC, merged