Feature: Refactor DC Outer Loops creation
powsybl/powsybl-open-loadflow pull request #1158
Opened 2024-12-18 15:18 UTC by vmouradian

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Part of #1091 + adds consistency (imo)

**What kind of change does this PR introduce?**

Feature

- DC Outerloops creation is made more consistent with AC ones (created in the OLF parameters class then are contained in DcLoadFlowParameters)

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-12-20 09:22 UTC, vmouradian commented
Support of OuterLoopNames parameters for DC is in this separated PR : #1159.
Can be merged into this branch or to main later

2025-01-03 09:08 UTC, jeandemanged requested changes

2025-01-03 09:08 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
> +            outerLoops.removeIf(DcAreaInterchangeControlOuterLoop.class::isInstance);
don't remove the outerloop here.
the outerloop should handle the 'no area' situation by itself.

2025-01-03 09:08 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractAreaInterchangeControlOuterLoop.java
> +        implements ActivePowerDistributionOuterLoop<V, E, P, C, O> {
since AbstractActivePowerDistributionOuterLoop implements ActivePowerDistributionOuterLoop, this part is redundant and can be removed too

```java
implements ActivePowerDistributionOuterLoop<V, E, P, C, O>
```

2025-01-03 17:34 UTC, SylvestreSakti commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +            DcIncrementalPhaseControlOuterLoop phaseShifterControlOuterLoop = new DcIncrementalPhaseControlOuterLoop();
Hello, a small remark here, maybe a little bit out of the scope of this PR : when comparing with `createAcOuterLoops`, it shows that the parameter **phaseShifterControlMode** is not taken into account in DC mode. Maybe it should be mentioned in the doc (or even with a log message, because default value of this param is `CONTINUOUS_WITH_DISCRETISATION` and not `INCREMENTAL`)

2025-01-06 16:33 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
> +            outerLoops.removeIf(DcAreaInterchangeControlOuterLoop.class::isInstance);
This was done to reproduce the behavior of DC slack distribution (which is done before equations solving and not via an outerloop).
So in the existing implementation of the AIC outreloops in the "no area" case :
 - The AC one defaults to distributed slack outerloop
 - The DC one does not handles the case because it should be handled by the DC LF engine (distribute slack before the other computations)  

This is something that can be homogenized but I think it will be out of the scope of this refactoring

2025-01-06 16:35 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractAreaInterchangeControlOuterLoop.java
> +        implements ActivePowerDistributionOuterLoop<V, E, P, C, O> {
yes ! fixed in [929a5b8](https://github.com/powsybl/powsybl-open-loadflow/pull/1158/commits/929a5b85adca901e5823c81ae5eaffb28280f374)

2025-01-14 11:28 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +            DcIncrementalPhaseControlOuterLoop phaseShifterControlOuterLoop = new DcIncrementalPhaseControlOuterLoop();
@SylvestreSakti if we want t improve the doc for phaseShifterControlMode I think this should be done in a different PR.
The doc of this paraeter could be improved in the following way I guess (just from code reading) - that are not all related to this outerloop.
    - The parameter is only relevant for AC
    - in Continuous mode, only the phase shifter in active power controller mode are computed through the Newton Raphson. The current limiters are controlled by an outerloop.
    - In continuous mode, if the active target power taget is impossible to reach, the newton raphson will diverge. In incremental mode, the failure occurs in the incrementalPhaseControl outerloop that cannot reach a stable state. This makes it easier to troubleshoot the failure cause.

2025-01-14 11:28 UTC, vidaldid-rte approved these changes
Looks OK for me.

2025-01-14 14:28 UTC, jeandemanged approved these changes

2025-01-14 14:28 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
> +            outerLoops.removeIf(DcAreaInterchangeControlOuterLoop.class::isInstance);
homogenization has been done in this PR

2025-01-16 08:44 UTC, merged