Support outerLoopNames parameter in DC
powsybl/powsybl-open-loadflow pull request #1159
Opened 2024-12-19 14:54 UTC by vmouradian

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

outerLoopNames parameter has no impact on outer loops craetion in DC load flow 

**What is the new behavior (if this is a feature change)?**
outerLoopNames parameter is usable to select outer loops in DC load flow, smsilarly to what exists for AC

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2025-01-03 10:18 UTC, jeandemanged requested changes
* move all xxxxxOuterLoopConfig classes from `com.powsybl.openloadflow` to new package `com.powsybl.openloadflow.lf.outerloop.config`
* please enhance `outerLoopNames` description in `docs/loadflow/parameters.md`: mention used for both AC and DC, and list the currently existing outer loops.

2025-01-03 10:18 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/OuterLoopConfig.java
> +    static <C extends OuterLoopConfig> Optional<C> findOuterLoopConfig(Class<C> configClass) {
```suggestion
    static <C extends OuterLoopConfig<?>> Optional<C> findOuterLoopConfig(Class<C> configClass) {
```

2025-01-03 11:39 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/OuterLoopConfig.java
oh my bad ! of course
fixed in [0ed4046](https://github.com/powsybl/powsybl-open-loadflow/pull/1159/commits/0ed40465eb504ad082c6fe064eac9c994489f417)

2025-01-03 12:34 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/OuterLoopConfig.java
I wasn't clear ... by "keep both" I meant leave the existing ones and add new ones:
- Leave the existing one because it was there and part of existing code is still used.
- Add new one because you introduce significant change.

for both copyright and author

2025-01-16 10:29 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/lf/outerloop/config/OuterLoopConfig.java
done in 52503cc36775d1341f7d43c85cc84d006be7cd32 and b666c0be3d1c60594f39b9ae29cdc01a68ee96a6

2025-01-16 12:45 UTC, jeandemanged approved these changes

2025-01-16 15:37 UTC, vidaldid-rte commented on docs/loadflow/parameters.md
> +(as defined in `DefaultAcOuterLoopConfig` for AC Load Flow and `DefaultDcOuterLoopConfig` for DC Load Flow).
Can you add that the list of outerloops is derived from the loadflow parameters (and give as example that useReactiveLimits actives the ReactiveLimitsOuterLoop in AC.
Can you also add that this parameter is an advanced parameters. When used other high level parameters such useReactiveLimits, transformaterVoltageControlOn etc... might be ignored).

2025-01-17 07:59 UTC, jeandemanged commented on docs/loadflow/parameters.md
> +(as defined in `DefaultAcOuterLoopConfig` for AC Load Flow and `DefaultDcOuterLoopConfig` for DC Load Flow).
done, should be better now

2025-01-17 13:06 UTC, SylvestreSakti commented on src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlOuterLoop.java
> -        return "AreaInterchangeControl";
This method `getName()` can be moved to the parent abstract class `AbstractAreaInterchangeControlOuterLoop`

2025-01-17 13:07 UTC, SylvestreSakti commented on src/main/java/com/powsybl/openloadflow/dc/DcIncrementalPhaseControlOuterLoop.java
> -        return "DC Incremental phase control";
Same here with the class `AbstractIncrementalPhaseControlOuterLoop`

2025-01-20 10:06 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlOuterLoop.java
> -        return "AreaInterchangeControl";
thanks ! done in [05ccafe](https://github.com/powsybl/powsybl-open-loadflow/pull/1159/commits/05ccafe0a606b58396b3e89dc26635c62462274a)

2025-01-20 10:06 UTC, vmouradian commented on src/main/java/com/powsybl/openloadflow/dc/DcIncrementalPhaseControlOuterLoop.java
> -        return "DC Incremental phase control";
done in [05ccafe](https://github.com/powsybl/powsybl-open-loadflow/pull/1159/commits/05ccafe0a606b58396b3e89dc26635c62462274a)

2025-01-29 12:42 UTC, vidaldid-rte commented on src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlOuterLoop.java
> -        return "AreaInterchangeControl";
Thanks. Closing the thread.

2025-01-31 08:34 UTC, merged