issue 110 mise en place des variables
powsybl/powsybl-open-loadflow pull request #144
Opened 2020-09-03 13:07 UTC by jeanChristopheGuillotin

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2020-09-03 14:40 UTC, annetill requested changes
You must change the class ````LfAbstractBus```` and build a unit test to improve this dev?

2020-09-03 14:40 UTC, annetill commented on src/main/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadOuterLoop.java
> +            double newVariableActivePower = variableActivePower - remainingMismatch * factor;
You must change the way the factors are computed.

2020-09-03 14:40 UTC, annetill commented on src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
> +        return 0;
You must return the attribute.

2020-09-03 14:40 UTC, annetill commented on src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
> +        return 0;
You must return the attribute.

2020-09-09 12:52 UTC, annetill commented
I will review as soon as possible. Can you see with Marco for the next issue that consists in keeping the power factor constant ? Thanks ! You can start from master branch, we will merge this PR later after review process.

2020-09-10 13:25 UTC, floriand-e2r commented on src/main/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadOuterLoop.java
>                  bus.setLoadTargetP(newTargetP);
Hello @annetill, in fact I think it is better to have the absolute value of the load fixed part. Indeed, here you need to update the ratio each time you change the load target. If you're dealing with the fixed part in absolute value, you don't have that problem

2020-09-11 08:55 UTC, floriand-e2r approved these changes
I don't see the benefit to use the per unit here, but it seems that it's the usual practice?

2020-09-11 11:43 UTC, merged