Add slackBusPMaxMismatch parameter
powsybl/powsybl-open-loadflow pull request #279
Opened 2021-04-21 13:05 UTC by obrix

Add slackBusPMaxMismatch  parameter with a default value of 0.01

2021-04-22 11:10 UTC, annetill requested changes
How does it work? With your PR, you are able to change a parameter, but where is this parameter used in the code? Then, you have to reach 90% of test coverage in OLF.

2021-04-22 11:40 UTC, obrix commented
@annetill This is a new attribute in OpenLoadFlowParameter class, it is used the same way as other parameters like throwsExceptionInCaseOfSlackDistributionFailure.
I just plugged it into DistributedSlackOuterLoop class constructor which is the reference you gave to me. If you think it should also be passed elsewhere, let me know. Coverage is fixed now that the parameter is used.

2021-04-23 07:21 UTC, geofjamg requested changes

2021-04-23 07:21 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +    private double slackBusPMaxMismatch = SLACK_BUS_P_MAX_MISMATCH_DEFAULT_VALUE / PerUnit.SB;
You should keep it in MW in the parameters

2021-04-23 07:21 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/ac/DistributedSlackOuterLoop.java
> +        if (Math.abs(slackBusActivePowerMismatch) > slackBusPMaxMismatch) {
This is here that you should convert to PU

2021-04-23 07:25 UTC, annetill commented on src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
> +        this.slackBusPMaxMismatch = pSlackBusPMaxMismatch / PerUnit.SB;
I get it, so I remove the per unit here.

2021-04-25 20:19 UTC, geofjamg approved these changes

2021-04-26 06:27 UTC, merged