Fix transformer control outerloop `AFTER_GENERATOR_VOLTAGE_CONTROL`
powsybl/powsybl-open-loadflow pull request #450
Opened 2022-02-17 11:04 UTC by annetill

- Add target deadband management.

Signed-off-by: Anne Tilloy <anne.tilloy@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-02-23 08:45 UTC, AnkurArohi requested changes

2022-02-23 08:45 UTC, AnkurArohi commented on src/main/java/com/powsybl/openloadflow/network/ShuntVoltageControl.java
> +        super(controlled, targetValue, 0.0);
Here we set by  the value of dead band as zero(is a fixed value, should ideally be used as a parameter or as a property that could be set by the user), is that correct? Furthermore, in TransformerVoltagecontrolouterloop , this value is used to check if voltage lies beyond this point, in order to set the voltageControl as true

2022-02-28 20:58 UTC, geofjamg requested changes

2022-02-28 20:58 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/ac/TransformerVoltageControlOuterLoop.java
> +    private List<LfBus> disabledControllerBuses = new ArrayList<>();
Disabled but never restored?
Also, we have to think about state management in outer loops, we should keep them stateless if possible to be able later to parallelize the security analysis more easily.

2022-03-14 13:21 UTC, annetill commented
Nothing is really important in that PR, I prefer to close it and reopen subjects later such as shunts' deadband.

2022-03-14 13:21 UTC, closed without merging