Adapt openloadflow to new status for security analysis.
powsybl/powsybl-open-loadflow pull request #638
Opened 2022-10-25 14:30 UTC by obrix

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

Adapt openloadflow to new status present in PreContingencyResult PostContingencyResult and OperatorStrategyResult.

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-11-04 12:18 UTC, geofjamg requested changes

2022-11-04 12:18 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +                return PostContingencyComputationStatus.CONVERGED;
throw an exception instead?

2022-11-04 12:18 UTC, geofjamg commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +                return LoadFlowResult.ComponentResult.Status.FAILED;
we should explicitely map all the enum and throws an exception in the defaut case.

2022-11-07 07:33 UTC, geofjamg approved these changes

2022-11-07 10:11 UTC, annetill approved these changes

2022-11-07 10:13 UTC, merged