Test Metrix for violations in Current, Voltage, Active and Apparent Power
powsybl/powsybl-open-loadflow pull request #650
Opened 2022-11-14 16:15 UTC by caioluke

ADD: Test Metrix for violations in Current, Voltage, Active and Apparent Power.

Signed-off-by: cluke <caio.luke@artelys.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-11-15 07:56 UTC, annetill requested changes
After just a quick look, I think that you have to create a dedicated factory in order to ass the limits you are using in your tests. In the same network, you can add current, apparent power and active power limits without any conflict. You have to tried to find coherent values and it is better not to change network characteristics (or to explain why you do that). After that, even in tests, we must avoid code duplication. I am sure you can find a way!

2023-03-02 13:11 UTC, geofjamg commented
What is the status of this PR?

2023-03-02 18:01 UTC, annetill commented
> What is the status of this PR?

As I said in my comment, this should be done in a dedicated factory in order to be reusable. And the good practice is to find relevant values without any characterictics change.

2023-04-05 09:10 UTC, annetill approved these changes

2023-04-06 09:04 UTC, merged