Support t3wt pst action
powsybl/powsybl-open-loadflow pull request #849
Opened 2023-09-20 09:30 UTC by vmouradian

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**
This PR enables to apply a pst action on a Three Windings Transformer

**What is the current behavior?**
Three Windings Transformers are not supported by pst actions

**What is the new behavior (if this is a feature change)?**
Three Windings Transformers are supported by pst actions

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-09-20 15:58 UTC, Hadrien-Godard approved these changes

2023-09-21 08:43 UTC, annetill requested changes
Small clean needed, but functionally right.

2023-09-21 08:43 UTC, annetill commented on src/main/java/com/powsybl/openloadflow/network/LfAction.java
> +        if (side.isPresent()) {
You already have this need for `PropagatedContingency`, so we have to refactor to share code. Note that the initialization of leg number with `""` is not really nice. Better put something like:
````
 LfBranch branch = lfNetwork.getBranchById(side.isPresent() ? action.getTransformerId() + legNumber : action.getTransformerId());
````

2023-09-21 08:43 UTC, annetill commented on src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
> +                        if (network.getThreeWindingsTransformer(phaseTapChangerTapPositionAction.getTransformerId()) == null) {
same: could you try to refactor throws?

2023-09-27 18:35 UTC, annetill commented on src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
> -            if (controlledBranchId.equals(controllerBranchId)) {
@geofjamg this part is really strange: no memory of such a that kind of code that I don't really get.

2023-09-28 08:49 UTC, annetill approved these changes

2023-09-28 08:54 UTC, merged