Add parameter to enable/disable generators outside limits to control voltage
powsybl/powsybl-open-loadflow pull request #964
Opened 2024-01-23 11:54 UTC by caioluke

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Add a parameter

**What is the current behavior?**

It is currently not possible to decide if we want generators with targetP outside their limits to control voltage

**What is the new behavior (if this is a feature change)?**
A new parameter in OLFParameters will allow to decide if we accept generators with targetP outside active limits to control voltage, in case active limits are taken into account.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

2024-01-23 15:18 UTC, jeandemanged requested changes
renaming & cleanup to do

2024-01-23 15:18 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
> +            LOGGER.warn("Network {}: {} generators have been discarded from voltage control because targetP is outside active limits",
outside active power limits

2024-01-23 15:18 UTC, jeandemanged commented on src/main/java/com/powsybl/openloadflow/util/Reports.java
> +                .withDefaultMessage("${impactedGeneratorCount} generators have been discarded from voltage control because targetP is outside active limits")
outside active power limits

2024-01-23 15:18 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
> +import com.powsybl.openloadflow.graph.EvenShiloachGraphDecrementalConnectivityFactory;
should not have to import all this here

2024-01-23 15:18 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
> +        LfNetworkParameters networkParameters = acLoadFlowParameters.getNetworkParameters();
Just create your LfNetworkParameters directly

        LfNetworkParameters parameters = new LfNetworkParameters()
                .setFoo(true);

2024-01-24 10:32 UTC, geofjamg requested changes
New parameter is missing in the specific parameter meta description list

2024-01-25 12:01 UTC, geofjamg approved these changes

2024-01-25 13:24 UTC, jeandemanged requested changes
one small minor insignificant remaining tiny issue

2024-01-25 13:24 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
> +        // discarded from voltage control because targetP > maxP (250 < 200)
```suggestion
        // discarded from voltage control because targetP > maxP (250 > 200)
```

2024-01-26 10:37 UTC, merged